### ISSUE TITLE
Compose key typing backslash

### ISSUE THREAD

**Issue by WizardMaggot** [WizardMaggot/Dvorak-Qwerty-Programming#2]
Issue proposed by Elyviere

https://www.reddit.com/r/dvorak/comments/oeebx3/programmer_dvorak_with_qwerty_shortcuts/h47rh1q?utm_source=share&utm_medium=web2x&context=3

**Comment by WizardMaggot** [comment]
It really doesn't help that I don't have a keyboard without a compose key

**Comment by Elyviere** [comment]
If you download sharpkeys, you can "pretend" to have a compose key on your keyboard. Change some useless key like the Application key to be your compose key. The compose key is called "Special: ISO extra key (00_56)" in swiftkey. 

Then you can use the application key as your compose key, which should make it easy to work on the above issue, and I'm sure you'll also quickly notice how valuable a compose key is.

**Comment by WizardMaggot** [comment]
> 
> 
> If you download sharpkeys, you can "pretend" to have a compose key on your keyboard. Change some useless key like the Application key to be your compose key. The compose key is called "Special: ISO extra key (00_56)" in swiftkey.
> 
> Then you can use the application key as your compose key, which should make it easy to work on the above issue, and I'm sure you'll also quickly notice how valuable a compose key is.

What I meant about the difficulty is not having a physical key to test out the function. Sharpkeys only modifies the registry to rebind keys. 
![image](https://user-images.githubusercontent.com/73365161/128429489-60f9d94e-fdf5-48e1-909f-ec32a85df4b7.png)

I might be able to emulate the compose key and try to see if I could output a scan code or something, though.

**Comment by Elyviere** [comment]
I'm saying that by using sharp keys, you trick windows into you having that physical key. 

Your keyboard already correctly identifies the physical key as the "Special: ISO extra key (00_56)" when I press it, which is the same as Kaufman's programmer dvorak layout. What differs is what gets written when it is pressed. The keys are the same in both your and his layout.

**Comment by WizardMaggot** [comment]
I used a stock Qwerty-International layout.
Looks like MS keyboard layout creator might not work at all for things like this, I'll try experimenting more.
Would you also list a Windows keyboard layout that works with your compose key? Thanks.

**Comment by Elyviere** [comment]
I'd suggest contacting kaufmann who created the original programmer dvorak layout, as I believe he used MS keyboard layout creator and he managed to get it to work. I also found some info on how a compose key can be created for windows on wikipedia, but that unfortunately seems more complex. https://en.wikipedia.org/wiki/Compose_key#Windows
I don't believe there are any native windows layouts with a compose key, but obviously Kaufmann's programmer dvorak does, in case that helps.

**Comment by WizardMaggot** [comment]
@Elyviere 
Kaufmann used a driver
![oaeu](https://user-images.githubusercontent.com/73365161/131427391-e0a1e6f7-bb21-48d8-8f33-9dc96eada059.png)
He did mention his driver integrating into the microsoft keyboard layouts, though. 
I'm not sure if it's true native - I don't think it is

**Comment by Elyviere** [comment]
Ah, that's unfortunate, probably not possible in native MSKLC then. Europeans will just have to stick with kaufmann's version.

**Comment by WizardMaggot** [comment]
You can try [wincompose](http://wincompose.info/) with my layout though, I think it works if you just use your compose key instead of ctrl-alt.
